import assert from "node:assert/strict";
import test from "node:test";

import { retargetLockedVersion } from "../scripts/sync-cargo-lock.mjs";

const lock = (verseVersion) => `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "anyhow"
version = "1.0.86"

[[package]]
name = "verse"
version = "${verseVersion}"
dependencies = [
 "anyhow",
]

[[package]]
name = "zip"
version = "0.6.6"
`;

test("only the locked verse package moves, byte for byte", () => {
  const result = retargetLockedVersion(lock("0.4.3"), "0.4.4");
  assert.equal(result.changed, true);
  assert.equal(result.from, "0.4.3");
  assert.equal(result.text, lock("0.4.4"));
});

test("a lock already on the release version is left untouched", () => {
  const result = retargetLockedVersion(lock("0.4.4"), "0.4.4");
  assert.equal(result.changed, false);
  assert.equal(result.text, undefined);
});

test("a lock without the package is refused instead of silently passing", () => {
  assert.throws(
    () => retargetLockedVersion('[[package]]\nname = "anyhow"\nversion = "1"\n', "0.4.4"),
    /no \[\[package\]\] named verse/,
  );
});

test("an ambiguous lock is refused rather than half-updated", () => {
  const ambiguous = `${lock("0.4.3")}
[[package]]
name = "verse"
version = "0.0.1"
`;
  assert.throws(() => retargetLockedVersion(ambiguous, "0.4.4"), /2 \[\[package\]\] entries/);
});

test("a neighbouring package with a similar name is not mistaken for it", () => {
  const neighbour = `[[package]]
name = "verse-lib"
version = "0.1.0"

[[package]]
name = "verse"
version = "0.4.3"
`;
  const result = retargetLockedVersion(neighbour, "0.4.4");
  assert.equal(result.from, "0.4.3");
  assert.match(result.text, /name = "verse-lib"\nversion = "0\.1\.0"/);
  assert.match(result.text, /name = "verse"\nversion = "0\.4\.4"/);
});
