//! Invariants over the committed MusicXML rhythm corpus.
//!
//! The corpus is generated by `scripts/generate-rhythm-corpus.py` with music21
//! and committed, so these tests run offline with no Python. music21 is an
//! independent producer, not an oracle: it writes shapes a hand-written fixture
//! would not think of — `<divisions>` stated once per part, `<voice>` omitted
//! for single-voice music, an XML comment before every measure, content-hash
//! part IDs — over rhythms chosen to be hard.
use std::fs;
use std::path::PathBuf;
use verse_lib::engine::convert::{convert_auto, ConvertOutcome};
use verse_lib::engine::projection::ProjectedProject;
use verse_lib::engine::target::{self, ExportTarget};

/// One quarter note in Synthesizer V blicks, and in OpenUtau ticks.
const BLICKS_PER_QUARTER: u64 = 705_600_000;
const USTX_TICKS_PER_QUARTER: u64 = 480;

fn corpus() -> Vec<(String, ConvertOutcome)> {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/corpora/rhythm");
    let mut paths: Vec<PathBuf> = fs::read_dir(&root)
        .unwrap_or_else(|error| panic!("the committed rhythm corpus is unreadable: {error}"))
        .flatten()
        .map(|entry| entry.path())
        .filter(|path| path.extension().and_then(|e| e.to_str()) == Some("musicxml"))
        .collect();
    paths.sort();
    assert!(
        paths.len() >= 4,
        "the rhythm corpus lost files; regenerate it with scripts/generate-rhythm-corpus.py"
    );
    paths
        .into_iter()
        .map(|path| {
            let name = path
                .file_stem()
                .unwrap_or_default()
                .to_string_lossy()
                .into();
            let bytes = fs::read(&path).expect("a committed corpus file is readable");
            (name, convert_auto(&bytes, "english"))
        })
        .collect()
}

fn projection<'a>(name: &str, outcome: &'a ConvertOutcome) -> &'a ProjectedProject {
    assert!(outcome.ok, "{name} failed to project: {:?}", outcome.msg);
    outcome
        .svp
        .as_ref()
        .unwrap_or_else(|| panic!("{name} produced no projection"))
}

/// Whether every position and duration divides exactly into a target's grid.
/// Computed rather than tabulated, so adding a corpus file needs no edit here.
fn lands_on(project: &ProjectedProject, quanta_per_quarter: u64) -> bool {
    let ticks_per_beat = u64::from(project.ticks_per_beat);
    project
        .tracks
        .iter()
        .flat_map(|track| &track.notes)
        .all(|note| {
            [note.onset_ticks, note.duration_ticks].iter().all(|ticks| {
                (u64::from(*ticks) * quanta_per_quarter).is_multiple_of(ticks_per_beat)
            })
        })
}

/// A tuplet is exactly where a rounding parser loses the source. `<divisions>`
/// is the denominator the file states, and every duration in it is an integer,
/// so the projection must carry that denominator rather than a convenient one.
#[test]
fn every_rhythm_keeps_the_divisions_the_file_states() {
    for (name, outcome) in corpus() {
        let project = projection(&name, &outcome);
        assert_eq!(
            project.ticks_per_beat, 10080,
            "{name}: music21 writes <divisions>10080</divisions> and nothing may round it"
        );
        for track in &project.tracks {
            for note in &track.notes {
                assert!(
                    note.duration_ticks > 0,
                    "{name}: a zero-length note is a rounded one"
                );
            }
        }
    }
}

/// Nested tuplets, meter changes and ties across barlines are exactly the
/// material an importer drops a syllable in. The count is the whole point: a
/// score that parses while losing one word reads as a success.
#[test]
fn no_syllable_of_the_corpus_is_lost_on_the_way_to_the_project() {
    for (name, outcome) in corpus() {
        let stated: usize = outcome
            .tracks
            .iter()
            .map(|track| track.lyric_status.source_text_count)
            .sum();
        assert!(stated > 0, "{name}: the corpus file must carry lyrics");
        assert_eq!(
            outcome.placed, stated,
            "{name}: every syllable the source writes must reach the project"
        );
    }
}

/// The invariant a vocal lane exists to hold. A stack in one lane makes
/// OpenUtau refuse the export and Synthesizer V sing one note of it.
#[test]
fn no_lane_of_the_corpus_sounds_two_notes_at_once() {
    for (name, outcome) in corpus() {
        let project = projection(&name, &outcome);
        assert_eq!(
            project.monophony_violation(),
            None,
            "{name}: a projection lane is not monophonic"
        );
        for track in &project.tracks {
            assert!(
                track
                    .notes
                    .windows(2)
                    .all(|pair| pair[0].onset_ticks <= pair[1].onset_ticks),
                "{name}: lane {} is not in ascending onset order",
                track.name
            );
        }
    }
}

/// The two grids differ, and the difference is the reason the export target is
/// part of the convertibility verdict. Blicks state every 10080th of a quarter;
/// 480 = 2^5 * 3 * 5 has no factor 7, so a septuplet has no place on it.
/// Refusing beats OpenUtau's own importer, which truncates the division.
#[test]
fn each_target_accepts_exactly_the_rhythms_its_own_grid_states() {
    for (name, outcome) in corpus() {
        let project = projection(&name, &outcome);
        for (export, quanta) in [
            (ExportTarget::Svp, BLICKS_PER_QUARTER),
            (ExportTarget::Ustx, USTX_TICKS_PER_QUARTER),
        ] {
            let verdict = target::validate_for(export, project);
            assert_eq!(
                verdict.is_ok(),
                lands_on(project, quanta),
                "{name}: {export:?} must accept exactly what its grid states, not {verdict:?}"
            );
            if verdict.is_ok() {
                target::serialize_to(export, project).unwrap_or_else(|error| {
                    panic!("{name}: {export:?} cleared but failed: {error}")
                });
            }
        }
    }
}

/// Synthesizer V states every rhythm here, so at least one target must always
/// have something to write. A corpus every target refuses tests nothing.
#[test]
fn synthesizer_v_writes_every_rhythm_of_the_corpus() {
    for (name, outcome) in corpus() {
        let project = projection(&name, &outcome);
        let bytes = target::serialize_to(ExportTarget::Svp, project)
            .unwrap_or_else(|error| panic!("{name}: blicks state this rhythm: {error}"));
        let parsed: serde_json::Value =
            serde_json::from_slice(&bytes).expect("a Synthesizer V project is JSON");
        let written = parsed["tracks"]
            .as_array()
            .expect("tracks")
            .iter()
            .map(|track| track["mainGroup"]["notes"].as_array().map_or(0, Vec::len))
            .sum::<usize>();
        let projected: usize = project.tracks.iter().map(|track| track.notes.len()).sum();
        assert_eq!(
            written, projected,
            "{name}: the file must hold every projected note"
        );
    }
}
